name: tests

on:
  push:
    branches:
      - master
      - develop
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        phpunit: [10, 11, 12]
        laravel: [10, 11, 12, 13]
        include:
          - php: 8.5
            laravel: 13
            phpunit: 13
          - php: 8.4
            laravel: 13
            phpunit: 13
        exclude:
          - php: 8.5
            laravel: 10
          - php: 8.5
            laravel: 11
          - php: 8.4
            laravel: 10
          - php: 8.2
            laravel: 13
          - phpunit: 10
            laravel: 13
          - phpunit: 11
            laravel: 10
          - phpunit: 12
            laravel: 10
          - phpunit: 12
            laravel: 11
          - php: 8.2
            phpunit: 12

    name: PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with="laravel/framework=^${{ matrix.laravel }}" --with="phpunit/phpunit:^${{ matrix.phpunit }}" 

      - name: Execute tests
        run: vendor/bin/phpunit --display-deprecations --fail-on-deprecation

  paratests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]

    name: PHP ${{ matrix.php }} Paratest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "nunomaduro/collision" "brianium/paratest" --no-update
          composer update --prefer-dist --no-interaction --no-progress -W

      - name: Execute tests
        run: php vendor/bin/testbench package:test --parallel
        env:
          DB_CONNECTION: mysql
          DB_USERNAME: root
          DB_DATABASE: laravel
